# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

    # Root and boot file systems with UUIDs (from lsblk output)
  fileSystems."/" =
    { device = "/dev/disk/by-uuid/c6b11160-88fb-4b66-a875-4974b7f211ff";  # UUID for root partition (/)
      fsType = "ext4";  # Assuming ext4, update if different
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/EA9D-DE32";  # UUID for boot partition (/boot)
      fsType = "vfat";  # Assuming vfat for boot partition, update if different
      options = [ "fmask=0077" "dmask=0077" ];  # Boot partition options
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/039c8f5e-2cf2-4ab3-8d01-733f8fec6820"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp6s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp7s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp5s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
