local M = {
  lazy = false,
  symbol_map = {
    Text = '',
    Method = '',
    Function = '󰊕',
    Constructor = '',
    Field = '󰽐',
    Variable = '󰫧',
    Class = '󰨡',
    Interface = '',
    Module = '',
    Property = '',
    Unit = '',
    Value = 'λ',
    Enum = '',
    Keyword = '󱆟',
    Snippet = '',
    Color = '',
    File = '󰈔',
    Reference = '',
    Folder = '',
    EnumMember = '',
    Constant = '',
    Struct = '',
    Event = '',
    Operator = '',
    TypeParameter = '󰉺',
  },
}

return M
